name: LibriTTS
data_root: /cm/archive/nghiahnh/data/zact-metadata
train_manifest: libritts_train_manifest_V2.txt
valid_manifest: LT_dev_manifest.txt
use_precomputed: false
sampling_rate: 16000
dur_min: 1
dur_max: 16.6
n_words_min: 3
prompt_dur_max: 5 #seconds
prompt_reduced_factor: 0.8
down_factors: [2, 4, 5, 5]
batch_size: 16
num_workers: 8
vocab_size: 1024
pin_memory: true
cleaners: ['english_cleaners']
add_blank: False
seed: null
sil_phones: null