target_dim: 256
spk_dim: 256
cond_dim: 384
downsampling_stages: 1
hidden_dim: 1024
n_layers: 4
n_quantizers: 6
sigma_min: 1e-6
cfg_dropout_prob: 0.1
guidance_scale: 3.5
convnext:
  kernel_size: 3
  stride: 1
  padding: 1
  expand: 1
  groups: 128
